
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN apt-get update && apt-get install -y dos2unix
RUN find /app -type f -print0 | xargs -0 dos2unix
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/out .
RUN apt-get update && apt-get install -y dos2unix
RUN find /app -type f -print0 | xargs -0 dos2unix
ENTRYPOINT ["dotnet", "WebApplicationIC.dll"]

# FROM mcr.microsoft.com/dotnet/core/runtime:2.2

# COPY WebApplicationIC/WebApplicationIC/bin/Release/netcoreapp2.2/publish/ app/

# RUN apt-get update && apt-get install -y dos2unix
# RUN find /app -type f -print0 | xargs -0 dos2unix

# ENTRYPOINT ["dotnet", "app/WebApplicationIC.dll"]